# Generated by Django 3.2.12 on 2023-05-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_farmer',
            field=models.BooleanField(default=False),
        ),
    ]
